package comp352_Assignment4;

public class driver {
	
	public static void main (String[] args){
		
		HashTable test1 = new HashTable();

		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		test1.put("hello", "hello");
		System.out.println(test1.size());
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		System.out.println(test1.size());
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		System.out.println(test1.size());
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		System.out.println(test1.size());
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		System.out.println(test1.size());
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		test1.put("test", "test");
		System.out.println(test1.size());
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		System.out.println(test1.size());
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		test1.put("apple", "apple");
		test1.keySet();
		test1.entrySet();

	}
}
